### ISSUE TITLE
"HttpListenerException: Zugriff verweigert" when using winwoof.exe without admin privileges

### ISSUE THREAD

**Issue by KarlK90** [rbeier/winwoof#1]
Error occures when invoking winwoof without admin privileges. 

Steps to reproduce:
1. open console
2. run `winwoof.exe README.md`
3. exception is thrown

Error Message:
```
Unbehandelte Ausnahme: System.Net.HttpListenerException: Zugriff verweigert
   bei System.Net.HttpListener.AddAllPrefixes()
   bei System.Net.HttpListener.Start()
   bei Winwoof..ctor(String[] args)
   bei Winwoof.Main(String[] args)
```

Further Read:
https://stackoverflow.com/questions/4019466/httplistener-access-denied

**Comment by rbeier** [comment]
fixed error by merged pull request.
